export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const ACCESS_KEY = 'Z3eo-W_HSYGhQE3TmJEAybRMAko7f2WsFmnzOK2j-TM';
export const SECRET_KEY = 'sAv_aE7wzxFhfRTCbMf-VmwZ8l6zMpgjF98QkYJnpRE';
export const REDIRECT_URI = 'http://127.0.0.1:5500/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';